import { onCall, HttpsError } from 'firebase-functions/v2/https'
import { onDocumentWritten } from 'firebase-functions/v2/firestore'
import { initializeApp } from 'firebase-admin/app'
import { FieldValue, getFirestore } from 'firebase-admin/firestore'
import { getStorage } from 'firebase-admin/storage'
import QRCode from 'qrcode'
import crypto from 'node:crypto'
initializeApp()
const db = getFirestore()
const role = async uid => (await db.doc(`users/${uid}`).get()).data()?.role
const number = () => `DT-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`

export const syncCatalogue = onDocumentWritten('inventory/{inventoryId}', async event => {
  const listingRef=db.doc(`catalogue/${event.params.inventoryId}`)
  if (!event.data?.after.exists) return listingRef.delete()
  const inventory=event.data.after.data(), drugSnap=await db.doc(`drugs/${inventory.drugId}`).get()
  if (!drugSnap.exists || drugSnap.data().status!=='ACTIVE') return listingRef.delete()
  const drug=drugSnap.data(), available=Math.max(0,Number(inventory.quantity||0)-Number(inventory.reservedQuantity||0))
  return listingRef.set({inventoryId:event.params.inventoryId,drugId:inventory.drugId,batchId:inventory.batchId,name:drug.name,genericName:drug.genericName||'',brandName:drug.brandName||'',categoryId:drug.categoryId||'',dosageForm:drug.dosageForm||'',strength:drug.strength||'',imageUrl:drug.imageUrl||'',prescriptionRequired:!!drug.prescriptionRequired,price:Number(inventory.sellingPrice||drug.basePrice||0),availableQuantity:available,status:available?'IN_STOCK':'OUT_OF_STOCK',updatedAt:FieldValue.serverTimestamp()})
})

export const generateBatchVerification = onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Sign in required.');const{batchId}=request.data||{},uid=request.auth.uid,userRole=await role(uid),batchRef=db.doc(`drugBatches/${batchId}`),batch=await batchRef.get();if(!batch.exists)throw new HttpsError('not-found','Batch not found.');if(!(userRole==='ADMIN'||(userRole==='MANUFACTURER'&&batch.data().manufacturerId===uid)))throw new HttpsError('permission-denied','Not authorized.');const drug=await db.doc(`drugs/${batch.data().drugId}`).get();if(!drug.exists)throw new HttpsError('failed-precondition','Drug record not found.');const token=crypto.randomBytes(24).toString('hex'),verificationRef=db.collection('batchVerifications').doc(token),safe={token,batchId,drugName:drug.data().name,brandName:drug.data().brandName||'',manufacturerName:batch.data().manufacturerName||'',batchNumber:batch.data().batchNumber,manufacturingDate:batch.data().manufacturingDate,expiryDate:batch.data().expiryDate,status:batch.data().status||'ACTIVE',qualityStatus:batch.data().qualityStatus||'PENDING',createdAt:FieldValue.serverTimestamp()};const png=await QRCode.toBuffer(JSON.stringify({type:'drugtrack-batch',token}));const file=getStorage().bucket().file(`qr/batches/${batchId}/${token}.png`);await file.save(png,{contentType:'image/png',metadata:{cacheControl:'public,max-age=31536000'}});await verificationRef.set({...safe,qrStoragePath:file.name});await batchRef.update({verificationToken:token,qrStoragePath:file.name,updatedAt:FieldValue.serverTimestamp()});return{token,verificationUrl:`/verify/${token}`}
})
export const verifyBatch = onCall(async request=>{const{token}=request.data||{};if(!token)throw new HttpsError('invalid-argument','Verification token required.');const snap=await db.doc(`batchVerifications/${token}`).get();if(!snap.exists)return{valid:false,status:'NOT_FOUND'};const x=snap.data(),expiry=x.expiryDate?new Date(x.expiryDate):null,status=expiry&&expiry<new Date()?'EXPIRED':x.status;await db.collection('verificationAttempts').add({token,batchId:x.batchId,status,createdAt:FieldValue.serverTimestamp()});return{valid:status==='ACTIVE'||status==='APPROVED',drugName:x.drugName,brandName:x.brandName,manufacturerName:x.manufacturerName,batchNumber:x.batchNumber,manufacturingDate:x.manufacturingDate,expiryDate:x.expiryDate,status}
})

export const createOrder = onCall(async request => {
  if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in to place an order.')
  const uid = request.auth.uid
  if (await role(uid) !== 'CUSTOMER') throw new HttpsError('permission-denied', 'Only customers may place orders.')
  const { address, paymentMethod = 'CASH_ON_DELIVERY' } = request.data || {}
  if (!address?.fullName || !address?.addressLine1 || !address?.city) throw new HttpsError('invalid-argument', 'A complete delivery address is required.')
  const cartRef = db.doc(`carts/${uid}`), orderRef = db.collection('orders').doc()
  await db.runTransaction(async tx => {
    const cart = await tx.get(cartRef), items = cart.exists ? cart.data().items || [] : []
    if (!items.length) throw new HttpsError('failed-precondition', 'Your cart is empty.')
    const trusted=[]
    for (const item of items) { const inventoryRef=db.doc(`inventory/${item.inventoryId}`), inventory=await tx.get(inventoryRef); if(!inventory.exists) throw new HttpsError('not-found','Inventory is unavailable.'); const stock=inventory.data(), available=Number(stock.quantity)-Number(stock.reservedQuantity||0); if(!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>available) throw new HttpsError('failed-precondition','Insufficient stock available.'); const drug=await tx.get(db.doc(`drugs/${stock.drugId}`)); if(!drug.exists||drug.data().status!=='ACTIVE') throw new HttpsError('failed-precondition','A medicine is unavailable.'); trusted.push({inventoryRef,stock,item:{inventoryId:item.inventoryId,drugId:stock.drugId,batchId:stock.batchId,manufacturerId:drug.data().manufacturerId,sellerId:stock.ownerId,sellerType:stock.ownerType,quantity:item.quantity,unitPrice:Number(stock.sellingPrice),total:Number(stock.sellingPrice)*item.quantity,drugName:drug.data().name,imageUrl:drug.data().imageUrl||''}}) }
    if(new Set(trusted.map(x=>x.item.sellerId)).size!==1) throw new HttpsError('failed-precondition','Checkout supports one seller at a time.')
    const subtotal=trusted.reduce((sum,x)=>sum+x.item.total,0), data={orderNumber:number(),customerId:uid,sellerId:trusted[0].item.sellerId,sellerType:trusted[0].item.sellerType,destinationType:'CUSTOMER',destinationId:uid,items:trusted.map(x=>x.item),subtotal,deliveryFee:0,totalAmount:subtotal,paymentMethod,paymentStatus:'PENDING',orderStatus:'PENDING',deliveryAddress:address,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()}
    trusted.forEach(({inventoryRef,stock,item})=>tx.update(inventoryRef,{reservedQuantity:Number(stock.reservedQuantity||0)+item.quantity,updatedAt:FieldValue.serverTimestamp()}));tx.set(orderRef,data);tx.set(cartRef,{customerId:uid,items:[],subtotal:0,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(db.collection('notifications').doc(),{userId:uid,type:'ORDER_PLACED',title:'Order placed',message:`Your order ${data.orderNumber} was placed.`,relatedId:orderRef.id,isRead:false,createdAt:FieldValue.serverTimestamp()});tx.set(db.collection('auditLogs').doc(),{userId:uid,userRole:'CUSTOMER',action:'CREATE_ORDER',entityType:'order',entityId:orderRef.id,description:`Created ${data.orderNumber}`,metadata:{},timestamp:FieldValue.serverTimestamp()})
  });return {orderId:orderRef.id}
})

const transitions = { PENDING:['CONFIRMED','CANCELLED'], CONFIRMED:['PROCESSING','CANCELLED'], PROCESSING:['PACKED','CANCELLED'], PACKED:['SHIPPED'], SHIPPED:['OUT_FOR_DELIVERY'], OUT_FOR_DELIVERY:['DELIVERED'], DELIVERED:['COMPLETED'], COMPLETED:[], CANCELLED:[] }
export const updateOrderStatus = onCall(async request => {
  if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.')
  const { orderId, status } = request.data || {}, uid=request.auth.uid, userRole=await role(uid)
  const orderRef=db.doc(`orders/${orderId}`)
  await db.runTransaction(async tx=>{const snap=await tx.get(orderRef);if(!snap.exists)throw new HttpsError('not-found','Order not found.');const order=snap.data(), isSeller=order.sellerId===uid;if(!(userRole==='ADMIN'||isSeller))throw new HttpsError('permission-denied','You cannot update this order.');if(!transitions[order.orderStatus]?.includes(status))throw new HttpsError('failed-precondition','Invalid order status transition.');if(status==='CANCELLED'){for(const item of order.items){const invRef=db.doc(`inventory/${item.inventoryId}`),inv=await tx.get(invRef);if(inv.exists)tx.update(invRef,{reservedQuantity:Math.max(0,Number(inv.data().reservedQuantity||0)-Number(item.quantity)),updatedAt:FieldValue.serverTimestamp()})}}if(status==='COMPLETED'){for(const item of order.items){const invRef=db.doc(`inventory/${item.inventoryId}`),inv=await tx.get(invRef);if(inv.exists){const x=inv.data();tx.update(invRef,{quantity:Math.max(0,Number(x.quantity)-Number(item.quantity)),reservedQuantity:Math.max(0,Number(x.reservedQuantity||0)-Number(item.quantity)),updatedAt:FieldValue.serverTimestamp()})}}}tx.update(orderRef,{orderStatus:status,completedAt:status==='COMPLETED'?FieldValue.serverTimestamp():null,updatedAt:FieldValue.serverTimestamp()});tx.set(db.collection('notifications').doc(),{userId:order.customerId,type:`ORDER_${status}`,title:'Order update',message:`Your order ${order.orderNumber} is ${status.replaceAll('_',' ').toLowerCase()}.`,relatedId:orderId,isRead:false,createdAt:FieldValue.serverTimestamp()})});return {ok:true}
})

export const createShipment = onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Sign in required.');const{orderId,carrierName,trackingNumber,estimatedDelivery}=request.data||{},uid=request.auth.uid,userRole=await role(uid),orderRef=db.doc(`orders/${orderId}`),order=await orderRef.get();if(!order.exists)throw new HttpsError('not-found','Order not found.');if(!(userRole==='ADMIN'||order.data().sellerId===uid))throw new HttpsError('permission-denied','Not authorized.');if(order.data().orderStatus!=='PACKED')throw new HttpsError('failed-precondition','Only packed orders can be shipped.');const shipmentRef=db.collection('shipments').doc(),data={shipmentNumber:`DT-SHP-${String(Date.now()).slice(-6)}`,orderId,sourceType:order.data().sellerType,sourceId:order.data().sellerId,distributorId:order.data().sellerType==='DISTRIBUTOR'?order.data().sellerId:null,destinationType:order.data().destinationType,destinationId:order.data().destinationId,carrierName:carrierName||'',trackingNumber:trackingNumber||'',status:'CREATED',currentLatitude:null,currentLongitude:null,destinationLatitude:order.data().deliveryAddress?.latitude||null,destinationLongitude:order.data().deliveryAddress?.longitude||null,estimatedDelivery:estimatedDelivery||null,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};await db.runTransaction(async tx=>{tx.set(shipmentRef,data);tx.update(orderRef,{orderStatus:'SHIPPED',shipmentId:shipmentRef.id,updatedAt:FieldValue.serverTimestamp()});tx.set(db.collection('auditLogs').doc(),{userId:uid,userRole,action:'CREATE_SHIPMENT',entityType:'shipment',entityId:shipmentRef.id,description:`Created ${data.shipmentNumber}`,metadata:{orderId},timestamp:FieldValue.serverTimestamp()})});return{shipmentId:shipmentRef.id}
})

export const assignDeliveryStaff = onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Sign in required.');const{shipmentId,deliveryStaffId}=request.data||{},uid=request.auth.uid,userRole=await role(uid);if(userRole!=='ADMIN'&&userRole!=='DISTRIBUTOR')throw new HttpsError('permission-denied','Not authorized.');const shipmentRef=db.doc(`shipments/${shipmentId}`),staff=await db.doc(`deliveryStaff/${deliveryStaffId}`).get(),shipment=await shipmentRef.get();if(!shipment.exists||!staff.exists)throw new HttpsError('not-found','Shipment or delivery staff member not found.');if(userRole==='DISTRIBUTOR'&&shipment.data().distributorId!==uid)throw new HttpsError('permission-denied','Shipment is not assigned to your distributor.');await shipmentRef.update({assignedDeliveryStaffId:deliveryStaffId,status:'ASSIGNED',updatedAt:FieldValue.serverTimestamp()});await db.collection('notifications').add({userId:deliveryStaffId,type:'DELIVERY_ASSIGNED',title:'Delivery assigned',message:`You were assigned shipment ${shipment.data().shipmentNumber}.`,relatedId:shipmentId,isRead:false,createdAt:FieldValue.serverTimestamp()});return{ok:true}
})

export const updateShipmentTracking = onCall(async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Sign in required.');const{shipmentId,status,latitude,longitude,message,estimatedDelivery}=request.data||{},uid=request.auth.uid,userRole=await role(uid),ref=db.doc(`shipments/${shipmentId}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Shipment not found.');const shipment=snap.data(),authorized=userRole==='ADMIN'||(userRole==='DISTRIBUTOR'&&(shipment.distributorId===uid||shipment.sourceId===uid))||(userRole==='DELIVERY_STAFF'&&shipment.assignedDeliveryStaffId===uid);if(!authorized)throw new HttpsError('permission-denied','Not authorized to update tracking.');const lat=Number(latitude),lng=Number(longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new HttpsError('invalid-argument','Valid coordinates are required.');const nextStatus=status||shipment.status;await db.runTransaction(async tx=>{tx.update(ref,{status:nextStatus,currentLatitude:lat,currentLongitude:lng,estimatedDelivery:estimatedDelivery||null,updatedAt:FieldValue.serverTimestamp()});tx.set(db.collection('trackingEvents').doc(),{shipmentId,status:nextStatus,latitude:lat,longitude:lng,message:message||'Location updated',timestamp:FieldValue.serverTimestamp(),updatedBy:uid,updatedByRole:userRole})});return{ok:true}
})
