export const roleLinks = {
  ADMIN: [
    { label: 'Overview', to: '/admin' },
    { label: 'Users & Approvals', to: '/admin/users' },
    { label: 'Categories', to: '/admin/categories' },
    { label: 'Drug Master', to: '/admin/drugs' },
    { label: 'Global Batches', to: '/admin/batches' },
    { label: 'Global Inventory', to: '/admin/inventory' },
    { label: 'All Orders', to: '/admin/orders' },
    { label: 'Profile', to: '/admin/profile' },
  ],
  MANUFACTURER: [
    { label: 'Dashboard', to: '/manufacturer' },
    { label: 'My Drugs', to: '/manufacturer/my-drugs' },
    { label: 'Batches & QR', to: '/manufacturer/batches' },
    { label: 'Factory Inventory', to: '/manufacturer/inventory' },
    { label: 'Incoming Orders', to: '/manufacturer/orders' },
    { label: 'Order History', to: '/manufacturer/history' },
    { label: 'Profile', to: '/manufacturer/profile' },
  ],
  WAREHOUSE_MANAGER: [
    { label: 'Dashboard', to: '/warehouse' },
    { label: 'Inventory & Bins', to: '/warehouse/inventory' },
    { label: 'Profile', to: '/warehouse/profile' },
  ],
  DISTRIBUTOR: [
    { label: 'Dashboard', to: '/distributor' },
    { label: 'Distribution Stock', to: '/distributor/inventory' },
    { label: 'Orders & Dispatch', to: '/distributor/orders' },
    { label: 'Order History', to: '/distributor/history' },
    { label: 'Profile', to: '/distributor/profile' },
  ],
  PHARMACY: [
    { label: 'Dashboard', to: '/pharmacy' },
    { label: 'Order Medicines', to: '/pharmacy/order' },
    { label: 'My Purchases', to: '/pharmacy/purchases' },
    { label: 'Order History', to: '/pharmacy/history' },
    { label: 'Pharmacy Stock', to: '/pharmacy/my-inventory' },
    { label: 'Customer Orders', to: '/pharmacy/orders' },
    { label: 'Profile', to: '/pharmacy/profile' },
  ],
  HOSPITAL: [
    { label: 'Dashboard', to: '/hospital' },
    { label: 'Order Medicines', to: '/hospital/order' },
    { label: 'My Purchases', to: '/hospital/purchases' },
    { label: 'Order History', to: '/hospital/history' },
    { label: 'Department Stock', to: '/hospital/inventory' },
    { label: 'Hospital Orders', to: '/hospital/orders' },
    { label: 'Profile', to: '/hospital/profile' },
  ],
  DELIVERY_STAFF: [
    { label: 'Deliveries', to: '/delivery' },
    { label: 'Delivery History', to: '/delivery/history' },
    { label: 'Profile', to: '/delivery/profile' },
  ],
  CUSTOMER: [
    { label: 'Marketplace', to: '/shop' },
    { label: 'All Medicines', to: '/medicines' },
    { label: 'My Cart', to: '/cart' },
    { label: 'Active Orders', to: '/orders' },
    { label: 'Order History', to: '/history' },
    { label: 'Saved Addresses', to: '/addresses' },
    { label: 'Notifications', to: '/notifications' },
    { label: 'My Profile', to: '/profile' },
  ],
}
