export const ACCOUNT_STATUS = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  INACTIVE: 'INACTIVE',
})

export const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  READY_FOR_DISTRIBUTOR: 'READY_FOR_DISTRIBUTOR',
  DISTRIBUTOR_RECEIVED: 'DISTRIBUTOR_RECEIVED',
  DISTRIBUTOR_ACCEPTED: 'DISTRIBUTOR_ACCEPTED',
  DISTRIBUTOR_PROCESSING: 'DISTRIBUTOR_PROCESSING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  RECIPIENT_CONFIRMED: 'RECIPIENT_CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
})

export const LEGACY_ORDER_STATUS_MAP = Object.freeze({
  CONFIRMED: 'UNDER_REVIEW',
  READY_FOR_DISPATCH: 'READY_FOR_DISTRIBUTOR',
  SHIPPED: 'PROCESSING',
  OUT_FOR_DELIVERY: 'PROCESSING',
  DELIVERED: 'DELIVERED',
  RETURNED: 'REJECTED',
})

export const SHIPMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED_AT_HUB: 'ARRIVED_AT_HUB',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
})

export const normalizeOrderStatus = status => {
  const value = String(status || '').trim().toUpperCase()
  if (!value) return ORDER_STATUS.PENDING
  if (value in ORDER_STATUS) return ORDER_STATUS[value]
  return LEGACY_ORDER_STATUS_MAP[value] || value
}
