import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Boxes, CalendarClock, PackageCheck } from 'lucide-react'
import { subscribeInventory, expiryState } from '../../services/inventoryService'
import { useAuth } from '../../context/AuthContext'
import DashboardCard from '../../components/common/DashboardCard'
import PageHeader from '../../components/common/PageHeader'
import LoadingSpinner from '../../components/feedback/LoadingSpinner'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
const copy={MANUFACTURER:['Manufacturing command centre','Monitor production batches, manufacturer inventory, and medicines you own.'],WAREHOUSE_MANAGER:['Warehouse operations','Receive, store, pick, and protect batch-level stock.'],DISTRIBUTOR:['Distribution command centre','Coordinate warehouse inventory and downstream medicine movement.'],PHARMACY:['Pharmacy operations','Monitor sale-ready stock, low-stock risk, and medicine availability.'],HOSPITAL:['Hospital pharmacy command centre','Protect emergency and department medicine availability.'],DELIVERY_STAFF:['Delivery workspace','Your assigned deliveries and proof-of-delivery activity will appear here.'],ADMIN:['Platform overview','System-wide data is available through authorized administration tools.']}
export default function RoleDashboard({role}){const{currentUser}=useAuth(),[rows,setRows]=useState(null);useEffect(()=>{if(role==='ADMIN'||role==='DELIVERY_STAFF'){setRows([]);return undefined}return subscribeInventory(setRows,currentUser.uid)},[currentUser,role]);const stats=useMemo(()=>{const r=rows||[];return{records:r.length,units:r.reduce((s,x)=>s+Number(x.quantity||0),0),low:r.filter(x=>Number(x.quantity)<=Number(x.reorderLevel||0)).length,expiry:r.filter(x=>expiryState(x.expiryDate)!=='VALID').length}},[rows]);const chart=[{name:'Healthy',value:Math.max(0,stats.records-stats.low-stats.expiry),color:'#0f766e'},{name:'Low stock',value:stats.low,color:'#f59e0b'},{name:'Expiry risk',value:stats.expiry,color:'#ef4444'}].filter(x=>x.value>0);if(rows===null)return <LoadingSpinner/>;const [title,description]=copy[role]||[`${role} dashboard`,'Secure DrugTrack workspace.'];return <><PageHeader title={title} description={description}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><DashboardCard title={String(stats.records)} description="Inventory records" icon={Boxes}/><DashboardCard title={String(stats.units)} description="Tracked units" icon={PackageCheck}/><DashboardCard title={String(stats.low)} description="Low-stock alerts" icon={AlertTriangle}/><DashboardCard title={String(stats.expiry)} description="Expiry alerts" icon={CalendarClock}/></div><section className="panel mt-6 grid gap-6 p-6 md:grid-cols-[1fr_280px]"><div><h2 className="font-bold">Operational readiness</h2><p className="mt-2 text-sm text-slate-500">Metrics update from your authorized Firestore inventory records. No sample metrics are displayed when there is no operational data.</p></div><div className="h-40">{chart.length?<ResponsiveContainer><PieChart><Pie data={chart} dataKey="value" innerRadius={35} outerRadius={65}>{chart.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<p className="pt-12 text-center text-sm text-slate-400">No inventory data yet.</p>}</div></section></>}
